### ISSUE TITLE
No upper bound on time taken to createIrreducible call

### ISSUE THREAD

**Issue by nathantippy** [themadcreator/rabinfingerprint#5]
A hard upper limit to the time required to produce a random irreducible polynomial would be a nice feature.  Someone auditing the code would have some questions about the current trial-and-error approach.  It does not need to be fast but it does need to have a fixed upper bound.

public static Polynomial createIrreducible(int degree)

**Comment by themadcreator** [comment]
That's a fair point.

However, because we are using the finite field GF(2), the number of irreducible polynomials or degree N is bounded. On average, we should require only N trials before encountering an irreducible polynomial. This is only the expected number of trials, and there is some variance, but in practice I have found it to be sufficient.

Furthermore, most applications only generate the irreducible polynomial once (as a pre-process), and then re-use to compare fingerprints across various data.

Finally, I was not able to find a simple deterministic time-bounded method for generating random irreducible polynomials. Do you know of one?
